package:
  name: pushprox
  version: "0.2.0"
  epoch: 0
  description: Proxy to allow Prometheus to scrape through NAT etc.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/PushProx.git
      tag: v${{package.version}}
      expected-commit: 83cae523a829b055f26f20baa2201dec67ab6f37

  - uses: go/build
    with:
      packages: ./cmd/proxy
      output: ${{package.name}}-proxy
      ldflags: |
        -X main.Version=${{package.version}}
        -extldflags '-static'

subpackages:
  - name: ${{package.name}}-client
    description: pushprox-client binary
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/client/main.go
          output: ${{package.name}}-client
          ldflags: |
            -X main.Version=${{package.version}}
            -extldflags '-static'

  - name: ${{package.name}}-compat
    description: Compat package for ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/app
          ln -sf /usr/bin/${{package.name}}-client "${{targets.contextdir}}"/app/${{package.name}}-client
          ln -sf /usr/bin/${{package.name}}-proxy "${{targets.contextdir}}"/app/${{package.name}}-proxy

update:
  enabled: true
  git:
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-client
  pipeline:
    - name: "Basic Smoke Test"
    - runs: |
        pushprox-client --help
        pushprox-proxy --help
