package:
  name: rke2-runtime
  version: 1.33.2_rke2r1
  epoch: 0
  description: Rancher Kubernetes Engine 2 (RKE2) is a fully conformant Kubernetes distribution with minimal dependencies
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - containerd
      - containerd-shim-runc-v2
      - crictl
      - ctr
      - kubectl
      - kubelet
      - runc
      - runc

# using apk-v2 friendly spec version format for package version string
# need to transform version to match upstream tag: '1.33.2+rke2r1'
var-transforms:
  - from: ${{package.version}}
    match: ^(\d+)\.(\d+)\.(\d+)_([a-zA-Z]+\d*)([a-zA-Z]+\d+)$
    replace: ${1}.${2}.${3}+${4}${5}
    to: mangled-package-version

environment:
  contents:
    packages:
      - bash
      - build-base
      - ca-certificates-bundle
  environment:
    CGO_ENABLED: "1"
    CGO_CFLAGS: "-DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_USE_ALLOCA=1"
    PROG: "rke2"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/rke2
      tag: v${{vars.mangled-package-version}}
      expected-commit: 62de1b13c6405a51bb4804a1dae6c2a5a17cc090

  - uses: go/build
    with:
      packages: .
      output: rke2
      ldflags: |
        -X github.com/k3s-io/k3s/pkg/version.GitCommit=$(git rev-parse HEAD)
        -X github.com/k3s-io/k3s/pkg/version.Program=$PROG
        -X github.com/k3s-io/k3s/pkg/version.Version=v1.33.3+dev.9f193e62
        -X github.com/k3s-io/k3s/pkg/version.UpstreamGolang=go1.24.4
        -X github.com/rancher/rke2/pkg/images.DefaultRegistry=docker.io
        -X github.com/rancher/rke2/pkg/images.DefaultEtcdImage=rancher/hardened-etcd:v3.5.21-k3s1-build20250612
        -X github.com/rancher/rke2/pkg/images.DefaultKubernetesImage=rancher/hardened-kubernetes:v1.33.3-rke2r1-build20250716
        -X github.com/rancher/rke2/pkg/images.DefaultPauseImage=rancher/mirrored-pause:3.6
        -X github.com/rancher/rke2/pkg/images.DefaultRuntimeImage=rancher/rke2-runtime:v1.33.3-dev.9f193e62
        -X github.com/rancher/rke2/pkg/images.DefaultCloudControllerManagerImage=rancher/rke2-cloud-provider:v1.33.1-0.20250516163953-99d91538b132-build20250612

  - uses: strip

test:
  pipeline:
    - name: Test rke2 binary exists and runs
      runs: |
        rke2 --version

update:
  enabled: true
  github:
    identifier: rancher/rke2
    strip-prefix: v
    tag-filter: v1.33
