package:
  name: rke2-runtime
  version: 1.33.2.2.1
  epoch: 0
  description: Rancher Kubernetes Engine 2 (RKE2) is a fully conformant Kubernetes distribution with minimal dependencies
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - containerd
      - containerd-shim-runc-v2
      - crictl
      - ctr
      - kubectl
      - kubelet
      - runc

# using apk-v2 friendly spec version format for package version string
# need to transform version (1.33.2.2.1) to match upstream tag: '1.33.2+rke2r1'
var-transforms:
  - from: ${{package.version}}
    match: ^(\d+)\.(\d+)\.(\d+)\.(\d+)\.(\d+)$
    replace: ${1}.${2}.${3}+rke${4}r${5}
    to: tag-version
  - from: ${{package.version}}
    match: ^(\d+)\.(\d+)\.(\d+)\.(\d+)\.(\d+)$
    replace: ${1}.${2}.${3}-rke${4}r${5}
    to: image-version

environment:
  contents:
    packages:
      - bash
      - build-base
      - ca-certificates-bundle
      - curl
      - pigz
      - yq
  environment:
    CGO_ENABLED: "1"
    CGO_CFLAGS: "-DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_USE_ALLOCA=1"
    GOEXPERIMENT: boringcrypto
    BUILD_TAGS: "selinux,netgo,osusergo,no_stage,static_build,sqlite_omit_load_extension,no_embedded_executor,no_cri_dockerd"
    # Hardcoded values set by upstream 'version.sh' script
    # REF: https://github.com/rancher/rke2/blob/master/scripts/version.sh
    PROG: "rke2"
    K3S_PKG: "github.com/k3s-io/k3s"
    RKE2_PKG: "github.com/rancher/rke2"
    REGISTRY: "docker.io"
    ETCD_VERSION: "v3.5.21-k3s1"
    PAUSE_VERSION: "3.6"
    KUBERNETES_IMAGE_TAG: "v1.33.3-rke2r1"
    REPO: "rancher"
    CCM_VERSION: "v1.33.1-0.20250516163953-99d91538b132-build20250612"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/rke2
      tag: v${{vars.tag-version}}
      expected-commit: 62de1b13c6405a51bb4804a1dae6c2a5a17cc090

  - uses: go/bump
    with:
      deps: |-
        github.com/pion/interceptor@v0.1.39

  - uses: go/build
    with:
      packages: .
      tags: $BUILD_TAGS
      output: rke2
      ldflags: |
        -X ${K3S_PKG}/pkg/version.GitCommit=$(git rev-parse HEAD)
        -X ${K3S_PKG}/pkg/version.Program=${PROG}
        -X ${K3S_PKG}/pkg/version.Version=${{vars.tag-version}}
        -X ${K3S_PKG}/pkg/version.UpstreamGolang=$(go env GOVERSION)
        -X ${RKE2_PKG}/pkg/images.DefaultRegistry=${REGISTRY}
        -X ${RKE2_PKG}/pkg/images.DefaultEtcdImage=rancher/hardened-etcd:${ETCD_VERSION}-build20250612
        -X ${RKE2_PKG}/pkg/images.DefaultKubernetesImage=rancher/hardened-kubernetes:${KUBERNETES_IMAGE_TAG}
        -X ${RKE2_PKG}/pkg/images.DefaultPauseImage=rancher/mirrored-pause:${PAUSE_VERSION}
        -X ${RKE2_PKG}/pkg/images.DefaultRuntimeImage=${REPO}/${PROG}-runtime:v${{vars.image-version}}
        -X ${RKE2_PKG}/pkg/images.DefaultCloudControllerManagerImage=rancher/rke2-cloud-provider:${CCM_VERSION}

  - name: Generate Charts
    runs: |
      # Modify CHART_TMP and YAML_TMP to work with busybox mktemp
      # REF: https://github.com/rancher/rke2/blob/master/charts/build-chart.sh#L11-L12
      sed -i 's|: "${CHART_TMP:=.*|: "${CHART_TMP:=$(mktemp /tmp/tmpchart.XXXXXX).tar}"|' charts/build-chart.sh
      sed -i 's|: "${YAML_TMP:=.*|: "${YAML_TMP:=$(mktemp /tmp/tmpvalues.XXXXXX).yaml}"|' charts/build-chart.sh

      # Generate charts
      bash charts/build-charts.sh

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: compatibility package for rke2-runtime
    pipeline:
      - runs: |
          # Setup compat dirs
          mkdir -p ${{targets.contextdir}}/charts

          # Copy over generated chart files files
          cp -r /home/build/charts/*.yaml  ${{targets.contextdir}}/charts

          # cleanup
          rm ${{targets.contextdir}}/charts/chart_versions.yaml

test:
  pipeline:
    - name: Test rke2 binary exists and runs
      runs: |
        rke2 --version
        rke2 --help

# Matching upstream tag and transforming it back to apkv2 friendly format
# EX: '1.33.2+rke2r1' --> '1.33.2.2.1'
update:
  enabled: true
  version-transform:
    - match: ^(\d+)\.(\d+)\.(\d+)\+([a-zA-Z]+)(\d+)([a-zA-Z]+)(\d+)$
      replace: "${1}.${2}.${3}.${5}.${7}"
  ignore-regex-patterns:
    - '-rc'
  github:
    identifier: rancher/rke2
    strip-prefix: v
    use-tag: true
